# Generated by Django 5.0.7 on 2024-07-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_numerostelefonicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerostelefonicos',
            name='numero_telefono',
            field=models.CharField(max_length=11),
        ),
    ]
